sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - git submodule update --init --remote --recursive

install:
    - pip install tox-travis "virtualenv<14.0.0"

script:
    - tox

# List all environments configured in tox.ini to test them all using
# Travis CI!
#env:
#    - TOX_ENV=py32
#    - TOX_ENV=py33
#    - TOX_ENV=py34
#    - TOX_ENV=py35
#    - TOX_ENV=py36
